### PR TITLE
updated builder.bat and READme.txt

### PR DESCRIPTION
**Pull request by aryan5555github**
i updated builder.bat and READme.txt to provide more detailed info @Blank-c

### CODE REVIEW

**Comment by Blank-c** [comment]
I don't know how this can be useful?

**Comment by aryan5555github** [comment]
It will help new users

**Comment by Blank-c** [comment]
I don't think there are people who know nothing but want to use the stealer. And if they are, they can search the internet.

**Comment by aryan5555github** [comment]
wat abt tat user and those

**Comment by Blank-c** [comment]
> wat abt tat user and those

what?

**Comment by aryan5555github** [comment]
tat comment remember

**Comment by Blank-c** [comment]
Still I don't think this one is useful.

**Pull request closed without merging**
