### PR TITLE
D: Drive Steam check

### PR DESCRIPTION
**Pull request by noahmajors**
couldve been better but will now check if there is a steam installation in the D drive after checking C.

### CODE REVIEW

**Comment by Blank-c** [comment]
Isn't the Program Files folder always in C?

**Comment by noahmajors** [comment]
nope, turns out close to 30% of users keep the C drive clean and install most games on a secondary drive, which happens to be D most of the time.

**Comment by Blank-c** [comment]
Why not we just make it so that it follows the path inside the steam lnk file from start menu.

**Comment by noahmajors** [comment]
after checking around stackoverflow for potential edits in regards to your .lnk suggestion, it seems that there aren't any good choices unless we opt to use something similar to this:
`import sys
import win32com.client 

shell = win32com.client.Dispatch("WScript.Shell")
shortcut = shell.CreateShortCut("t:\\test.lnk")
print(shortcut.Targetpath)`

**Comment by Blank-c** [comment]
> 

I understood what to do, apparently you can use `wmic` to locate the targetpath of a .lnk file
I'll make an update soon.

**Comment by aryan5555github** [comment]
Good feature though

**Comment by Blank-c** [comment]
> Good feature though

I already added something better.

**Pull request closed without merging**
