### PR TITLE
battle.net + new steam features

### PR DESCRIPTION
**Pull request by noahmajors**
# Battle.net
now grabs battle.net session

# Steam updates
now uses steamid from loginusers.vdf to reach the steam web api to check for some information, such as games owned, account information, and account level. (plan to update this later to translate appid to game name)

### CODE REVIEW

**Comment by noahmajors** [comment]
ran into issues converting the api into txt

**Comment by Blank-c** [comment]
Lets leave the steam one

**Comment by noahmajors** [comment]
steam is broken. battle net is functional

**Comment by aryan5555github** [comment]
Then let's do the battlenet one @noahmajors

**Pull request closed without merging**
